# Supervised Learning- Classification
Problem Description

Use sklearn.datasets iris flower dataset to train your model using logistic regression. You need to figure out the accuracy of your model and use that to predict different samples in your test dataset. In iris dataset there are 150 samples containing following features,

Sepal Length

Sepal Width

Petal length

Petal width

Using above 4 features you will classify a flower in one of the three categories,

Setosa

Versicolour

Virginica

In [66]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris

In [2]:
#Dataset from sklearn

from sklearn.datasets import load_iris
iris = load_iris()
type(iris)

sklearn.utils._bunch.Bunch

In [3]:
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [4]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
iris_df= pd.DataFrame(data = iris['data'], columns = iris['feature_names'])
iris_df


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [8]:
iris_df['Iris category'] = iris['target']

In [9]:
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   Iris category  
0              0  
1              0  
2              0  
3              0  
4              0

In [12]:
iris_df['Species'] = iris_data['Iris category'].apply(lambda x: 'sentosa' if x == 0 else ('versicolor' if x == 1 else 'virginica'))


In [13]:
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   Iris category  Species  
0              0  sentosa  
1              0  sentosa  
2              0  sentosa  
3              0  sentosa  
4              0  sentosa

In [14]:
iris_df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     Iris category    Species  
145              2  virginica  
146              2  virginica  
147              2  virginica  
148              2  virginica  
149              2  virginica

# Data cleaning

In [17]:
iris_df.drop(columns='Iris category',inplace=True)

In [18]:
print("No of rows:",iris_df.shape[0])
print("No of columns:",iris_df.shape[1])

No of rows: 150
No of columns: 5


In [19]:
iris_df[iris_df.duplicated()]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
142                5.8               2.7                5.1               1.9   

       Species  
142  virginica

In [21]:
iris_df.drop_duplicates(inplace=True)
iris_df[iris_df.duplicated()]

Empty DataFrame
Columns: [sepal length (cm), sepal width (cm), petal length (cm), petal width (cm), Species]
Index: []

# 

# Data Preprocessing

In [22]:

iris_df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
Species              0
dtype: int64

# Label Encoding

In [24]:
from sklearn.preprocessing import LabelEncoder
Label=LabelEncoder()
iris_df['Species']=Label.fit_transform(iris_df['Species'])
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   Species  
0        0  
1        0  
2        0  
3        0  
4        0

# Splitting the dataset

In [27]:
from sklearn.model_selection import train_test_split
x=iris_df.drop(columns=['Species'])
y=iris_df['Species']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.40)

# Logistic Regression

In [28]:
from sklearn.linear_model import LogisticRegression

LR=LogisticRegression()
LR.fit(x_train,y_train)

C:\Users\user\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [29]:
y_predicted = LR.predict(x_test)
LR.predict_proba(x_test)

array([[2.88853136e-06, 1.99817841e-02, 9.80015327e-01],
       [5.79762544e-03, 8.04932555e-01, 1.89269819e-01],
       [2.52603985e-02, 8.23078444e-01, 1.51661157e-01],
       [9.65067848e-01, 3.49309689e-02, 1.18362562e-06],
       [9.79762967e-01, 2.02364489e-02, 5.84120622e-07],
       [9.58889635e-01, 4.11082453e-02, 2.11998040e-06],
       [6.21042802e-02, 9.18991033e-01, 1.89046869e-02],
       [9.78563126e-01, 2.14364929e-02, 3.81143766e-07],
       [1.69490135e-01, 8.22643461e-01, 7.86640381e-03],
       [3.01636000e-01, 6.94182175e-01, 4.18182553e-03],
       [1.26108223e-03, 4.09382367e-01, 5.89356551e-01],
       [9.78981963e-01, 2.10173157e-02, 7.21071873e-07],
       [9.66953394e-01, 3.30456625e-02, 9.43535216e-07],
       [2.52248011e-03, 6.91512740e-01, 3.05964779e-01],
       [9.36433747e-01, 6.35620387e-02, 4.21464906e-06],
       [4.95540512e-07, 9.41360006e-03, 9.90585904e-01],
       [1.43475102e-03, 3.81613935e-01, 6.16951314e-01],
       [9.59259089e-01, 4.07400

In [30]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.metrics import classification_report

In [31]:
y_predicted

array([2, 1, 1, 0, 0, 0, 1, 0, 1, 1, 2, 0, 0, 1, 0, 2, 2, 0, 2, 1, 1, 1,
       0, 0, 2, 2, 1, 0, 1, 2, 0, 1, 0, 1, 1, 2, 2, 2, 0, 0, 1, 0, 1, 1,
       1, 2, 1, 1, 0, 1, 2, 2, 0, 2, 2, 0, 0, 0, 2, 1])

In [32]:
print("Score :",LR.score(x_test,y_test))
print("Accuracy_score :",accuracy_score(y_test,y_predicted))
print('Confusion Matrix:', confusion_matrix(y_test,y_predicted))
print('F1 score:', f1_score(y_test,y_predicted, average='macro'))
print('Classification Report:',classification_report(y_test,y_predicted))

Score : 0.9833333333333333
Accuracy_score : 0.9833333333333333
Confusion Matrix: [[21  0  0]
 [ 0 22  1]
 [ 0  0 16]]
F1 score: 0.9824915824915825
Classification Report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       1.00      0.96      0.98        23
           2       0.94      1.00      0.97        16

    accuracy                           0.98        60
   macro avg       0.98      0.99      0.98        60
weighted avg       0.98      0.98      0.98        60



# Decision Tree

In [33]:
#Import the model
from sklearn.tree import DecisionTreeClassifier
#Fit the model
DTC=DecisionTreeClassifier()
DTC.fit(x_train,y_train)

DecisionTreeClassifier()

In [34]:
decypr=DTC.predict(x_test)
decypr

array([2, 1, 1, 0, 0, 0, 1, 0, 1, 1, 2, 0, 0, 1, 0, 2, 2, 0, 2, 1, 1, 1,
       0, 0, 2, 2, 1, 0, 1, 2, 0, 1, 0, 1, 1, 2, 2, 2, 0, 0, 1, 0, 1, 1,
       1, 2, 1, 1, 0, 1, 1, 2, 0, 2, 2, 0, 0, 0, 2, 1])

In [35]:
print('Score:',DTC.score(x_test,y_test))
print("Accuracy_score :",accuracy_score(y_test,decypr))
print('F1 score : ',f1_score(y_test, decypr, average='macro'))
print("confusion_matrix:",confusion_matrix(y_test,decypr), ['sentosa', 'versicolor', 'virginica'])
print(classification_report(y_test,decypr))

Score: 0.9666666666666667
Accuracy_score : 0.9666666666666667
F1 score :  0.9646739130434782
confusion_matrix: [[21  0  0]
 [ 0 22  1]
 [ 0  1 15]] ['sentosa', 'versicolor', 'virginica']
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       0.96      0.96      0.96        23
           2       0.94      0.94      0.94        16

    accuracy                           0.97        60
   macro avg       0.96      0.96      0.96        60
weighted avg       0.97      0.97      0.97        60



# Parameter Tuning of Decision Tree Classifier

In [36]:
parameter={
    'criterion':['gini','entropy'],
    'max_depth':[1,2,3,4,5],
    'max_features':['auto','sqrt','log2'],
    'splitter':['best', 'random']
}
from sklearn.model_selection import GridSearchCV
cv=GridSearchCV(DTC,parameter,scoring='accuracy')
cv.fit(x_train,y_train)

C:\Users\user\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
100 fits failed out of a total of 300.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
100 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\user\anaconda3\Lib\site-packages\sk

GridSearchCV(estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [1, 2, 3, 4, 5],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='accuracy')

In [37]:
best_model=cv.best_estimator_
DTC.fit(x_train, y_train)

DecisionTreeClassifier()

In [38]:
from sklearn import tree
path = DTC.cost_complexity_pruning_path(x_train, y_train)
ccp_alphas = path.ccp_alphas
print(ccp_alphas)

clfs = []
for ccp_alpha in ccp_alphas:
    clf = tree.DecisionTreeClassifier(random_state=0, ccp_alpha=ccp_alpha)
    clf.fit(x_train, y_train)
    clfs.append(clf)

[0.         0.00842697 0.0108735  0.04358776 0.25151917 0.3306022 ]


In [39]:
DTC_pred = best_model.predict(x_test)
DTC_pred

array([2, 1, 1, 0, 0, 0, 1, 0, 1, 1, 2, 0, 0, 1, 0, 2, 2, 0, 2, 1, 1, 1,
       0, 0, 2, 2, 1, 0, 1, 2, 0, 1, 0, 1, 1, 2, 2, 2, 0, 0, 1, 0, 1, 1,
       1, 2, 1, 1, 0, 1, 1, 2, 0, 2, 2, 0, 0, 0, 2, 1])

In [40]:
print("score:",best_model.score(x_test,y_test))
print("Accuracy score:",accuracy_score(y_test,DTC_pred))
print('F1 score :', f1_score(y_test,DTC_pred, average='macro'))
print('Confusion Matrix:', confusion_matrix(y_test, DTC_pred))
print('Classification Report :', classification_report(y_test, DTC_pred))

score: 0.9666666666666667
Accuracy score: 0.9666666666666667
F1 score : 0.9646739130434782
Confusion Matrix: [[21  0  0]
 [ 0 22  1]
 [ 0  1 15]]
Classification Report :               precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       0.96      0.96      0.96        23
           2       0.94      0.94      0.94        16

    accuracy                           0.97        60
   macro avg       0.96      0.96      0.96        60
weighted avg       0.97      0.97      0.97        60



# KNN

In [41]:
from sklearn.neighbors import KNeighborsClassifier
KNN= KNeighborsClassifier()
KNN.fit(x_train,y_train)

KNeighborsClassifier()

In [42]:
knnypr=DTC.predict(x_test)
knnypr

array([2, 1, 1, 0, 0, 0, 1, 0, 1, 1, 2, 0, 0, 1, 0, 2, 2, 0, 2, 1, 1, 1,
       0, 0, 2, 2, 1, 0, 1, 2, 0, 1, 0, 1, 1, 2, 2, 2, 0, 0, 1, 0, 1, 1,
       1, 2, 1, 1, 0, 1, 2, 2, 0, 2, 2, 0, 0, 0, 2, 1])

In [43]:
print('Score:',KNN.score(x_test,y_test))
print('Accuracy score:',accuracy_score(y_test,knnypr))
print('F1 score : ',f1_score(y_test,knnypr, average='macro'))
print("confusion_matrix:",confusion_matrix(y_test,knnypr), ['sentosa', 'versicolor', 'virginica'])
print(classification_report(y_test,knnypr))

Score: 0.9833333333333333
Accuracy score: 0.9833333333333333
F1 score :  0.9824915824915825
confusion_matrix: [[21  0  0]
 [ 0 22  1]
 [ 0  0 16]] ['sentosa', 'versicolor', 'virginica']
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       1.00      0.96      0.98        23
           2       0.94      1.00      0.97        16

    accuracy                           0.98        60
   macro avg       0.98      0.99      0.98        60
weighted avg       0.98      0.98      0.98        60



# Parameter Tuning of KNN 

In [45]:
from sklearn.neighbors import KNeighborsClassifier
param_grid ={
    'n_neighbors': [3, 5, 7, 9, 11], 
    'weights': ['uniform', 'distance',None],  
    'algorithm':['auto', 'ball_tree', 'kd_tree', 'brute']}
KNN = KNeighborsClassifier()
grid_search = GridSearchCV(estimator=KNN, param_grid=param_grid, scoring='accuracy', cv=5)
grid_search.fit(x_train, y_train)

C:\Users\user\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:824: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 813, in _score
    scores = scorer(estimator, X_test, y_test)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 266, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 353, in _score
    y_pred = method_caller(estimator, "predict", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", li

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [3, 5, 7, 9, 11],
                         'weights': ['uniform', 'distance', None]},
             scoring='accuracy')

In [46]:
best_params = grid_search.best_params_
print("Best Number of Neighbors:", best_params['n_neighbors'])
best_model = grid_search.best_estimator_
y_pred = best_model.predict(x_test)
accuracy = accuracy_score(y_test,y_pred)
print(f'Accuracy with Best Model: {accuracy:.2f}')
print('F1 score:', f1_score(y_test,y_pred, average='macro'))
print('Confusion Matrix:', confusion_matrix(y_test,y_pred))
print(' Classification Report:', classification_report(y_test,y_pred))

Best Number of Neighbors: 9
Accuracy with Best Model: 0.98
F1 score: 0.9824915824915825
Confusion Matrix: [[21  0  0]
 [ 0 22  1]
 [ 0  0 16]]
 Classification Report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       1.00      0.96      0.98        23
           2       0.94      1.00      0.97        16

    accuracy                           0.98        60
   macro avg       0.98      0.99      0.98        60
weighted avg       0.98      0.98      0.98        60



# Random Forest

In [47]:
from sklearn.ensemble import RandomForestClassifier
RF=RandomForestClassifier()
RF.fit(x_train,y_train)

RandomForestClassifier()

In [48]:
RF_y_pred=DTC.predict(x_test)
RF_y_pred

array([2, 1, 1, 0, 0, 0, 1, 0, 1, 1, 2, 0, 0, 1, 0, 2, 2, 0, 2, 1, 1, 1,
       0, 0, 2, 2, 1, 0, 1, 2, 0, 1, 0, 1, 1, 2, 2, 2, 0, 0, 1, 0, 1, 1,
       1, 2, 1, 1, 0, 1, 2, 2, 0, 2, 2, 0, 0, 0, 2, 1])

In [49]:
print("Score:",RF.score(x_test,y_test))
print('Accuracy score:',DTC.score(x_test,y_test))
print('F1 score : ',f1_score(y_test,RF_y_pred, average='macro'))
print("confusion_matrix:",confusion_matrix(y_test,RF_y_pred), ['sentosa', 'versicolor', 'virginica'])
print(classification_report(y_test,RF_y_pred))

Score: 0.9666666666666667
Accuracy score: 0.9833333333333333
F1 score :  0.9824915824915825
confusion_matrix: [[21  0  0]
 [ 0 22  1]
 [ 0  0 16]] ['sentosa', 'versicolor', 'virginica']
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       1.00      0.96      0.98        23
           2       0.94      1.00      0.97        16

    accuracy                           0.98        60
   macro avg       0.98      0.99      0.98        60
weighted avg       0.98      0.98      0.98        60



# Parameter Tuning of Random Forest Classifier

In [54]:
parameter={
    'n_estimators':[10,50,100],
    'criterion':['gini','entropy','log_loss'],
    'max_depth':np.arange(2,10,2),
    'max_features':[None,'sqrt','log2'],
    "bootstrap": [True, False]
    }

RF= RandomForestClassifier()

cv=GridSearchCV(RF,parameter,scoring='accuracy')
cv.fit(x_train,y_train)

GridSearchCV(estimator=RandomForestClassifier(),
             param_grid={'bootstrap': [True, False],
                         'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': array([2, 4, 6, 8]),
                         'max_features': [None, 'sqrt', 'log2'],
                         'n_estimators': [10, 50, 100]},
             scoring='accuracy')

In [55]:
print ('Random grid: ',parameter)
best_params = cv.best_params_
print ('Best Parameters: ',best_params)
best_f1_score =cv.best_score_
print("Best F1 Score:", best_f1_score)
best_model =cv.best_estimator_
best_model.fit(x_train,y_train)
RF_pred=best_model.predict(x_test)
print('Score:',best_model.score(x_test,y_test))
print('Accuracy score:',accuracy_score(y_test,RF_pred))
print('Confusion Matrix:', confusion_matrix(y_test,RF_pred))
print('Classification Report :',classification_report(y_test,RF_pred))

Random grid:  {'n_estimators': [10, 50, 100], 'criterion': ['gini', 'entropy', 'log_loss'], 'max_depth': array([2, 4, 6, 8]), 'max_features': [None, 'sqrt', 'log2'], 'bootstrap': [True, False]}
Best Parameters:  {'bootstrap': True, 'criterion': 'gini', 'max_depth': 2, 'max_features': 'sqrt', 'n_estimators': 10}
Best F1 Score: 0.9555555555555555
Score: 0.95
Accuracy score: 0.95
Confusion Matrix: [[21  0  0]
 [ 0 21  2]
 [ 0  1 15]]
Classification Report :               precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       0.95      0.91      0.93        23
           2       0.88      0.94      0.91        16

    accuracy                           0.95        60
   macro avg       0.95      0.95      0.95        60
weighted avg       0.95      0.95      0.95        60



# Ada Boost Classifier

In [58]:
from sklearn.ensemble import AdaBoostClassifier
Adaboost=AdaBoostClassifier()
Adaboost.fit(x_train,y_train)

AdaBoostClassifier()

In [59]:
Adaboost_pred=Adaboost.predict(x_test)
print("Score:",Adaboost.score(x_test,y_test))
print("Accuracy score:",accuracy_score(y_test,Adaboost_pred))
print("F1 Sore:",f1_score(y_test,Adaboost_pred,average='macro'))
print("confusion matrix:",confusion_matrix(y_test,Adaboost_pred))
print("Classification Report:",classification_report(y_test,Adaboost_pred))

Score: 0.9666666666666667
Accuracy score: 0.9666666666666667
F1 Sore: 0.9646739130434782
confusion matrix: [[21  0  0]
 [ 0 22  1]
 [ 0  1 15]]
Classification Report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       0.96      0.96      0.96        23
           2       0.94      0.94      0.94        16

    accuracy                           0.97        60
   macro avg       0.96      0.96      0.96        60
weighted avg       0.97      0.97      0.97        60



# SVC

In [60]:
from sklearn.svm import SVC
SV=SVC(kernel = 'rbf', C = 3)
SV.fit(x_train,y_train)

SVC(C=3)

In [61]:
SV_pred=SV.predict(x_test)
print("Score:",SV.score(x_test,y_test))
print("Accuracy score",accuracy_score(y_test,SV_pred))
print("F1 score:",f1_score(y_test,SV_pred,average='macro'))
print('Confusion matrix:',confusion_matrix(y_test,SV_pred))
print('Classification report:',classification_report(y_test,SV_pred))

Score: 0.9833333333333333
Accuracy score 0.9833333333333333
F1 score: 0.9824915824915825
Confusion matrix: [[21  0  0]
 [ 0 22  1]
 [ 0  0 16]]
Classification report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       1.00      0.96      0.98        23
           2       0.94      1.00      0.97        16

    accuracy                           0.98        60
   macro avg       0.98      0.99      0.98        60
weighted avg       0.98      0.98      0.98        60



# Support vector classifier with Parameter Tuning

In [62]:
param_grid = {
    'C': [0.1, 1, 3, 10],          
    'gamma': [0.001, 0.01, 0.1],  
}
grid_search = GridSearchCV(estimator=SV, param_grid=param_grid, scoring='f1_macro', cv=5)
grid_search.fit(x_train, y_train)
best_params = grid_search.best_params_
print("Best Hyperparameters:", best_params)
best_f1_score = grid_search.best_score_
print("Best F1 Score:", best_f1_score)
best_model = grid_search.best_estimator_

Best Hyperparameters: {'C': 10, 'gamma': 0.1}
Best F1 Score: 0.9539186739186739


In [63]:
SV_y_pred=grid_search.predict(x_test)
print("Score:",grid_search.score(x_test,y_test))
print("Accuracy score",accuracy_score(y_test,SV_y_pred))
print("F1 score:",f1_score(y_test,SV_y_pred,average='macro'))
print('Confusion matrix:',confusion_matrix(y_test,SV_y_pred))
print('Classification report:',classification_report(y_test,SV_y_pred))

Score: 1.0
Accuracy score 1.0
F1 score: 1.0
Confusion matrix: [[21  0  0]
 [ 0 23  0]
 [ 0  0 16]]
Classification report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       1.00      1.00      1.00        23
           2       1.00      1.00      1.00        16

    accuracy                           1.00        60
   macro avg       1.00      1.00      1.00        60
weighted avg       1.00      1.00      1.00        60



# Gradient Boosting Classifier

In [67]:
from sklearn.ensemble import GradientBoostingClassifier
Grboost=GradientBoostingClassifier()
Grboost.fit(x_train,y_train)

GradientBoostingClassifier()

In [68]:
Grboost_pred=Grboost.predict(x_test)
print('Score:',Grboost.score(x_test,y_test))
print('Accuracy score:',accuracy_score(y_test,Grboost_pred))
print('F1 Score:',f1_score(y_test,Grboost_pred,average='macro'))
print('Confusion matrix:',confusion_matrix(y_test,Grboost_pred))
print('Classification report:',classification_report(y_test,Grboost_pred))

Score: 0.9833333333333333
Accuracy score: 0.9833333333333333
F1 Score: 0.9824915824915825
Confusion matrix: [[21  0  0]
 [ 0 22  1]
 [ 0  0 16]]
Classification report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       1.00      0.96      0.98        23
           2       0.94      1.00      0.97        16

    accuracy                           0.98        60
   macro avg       0.98      0.99      0.98        60
weighted avg       0.98      0.98      0.98        60

